name: km_ui
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
